version: '3.8'

networks:
  jenkins-selenium:
    driver: bridge

services:
  selenium-hub:
    image: selenium/hub
    networks:
      - jenkins-selenium
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
  firefox:
    image: selenium/node-firefox
    networks:
      - jenkins-selenium
    shm_size: 1gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
  chrome:
    image: selenium/node-chrome:latest
    networks:
      - jenkins-selenium
    container_name: chrome-node
    shm_size: 1gb
    depends_on:
      - selenium-hub
    platform: linux/amd64
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
  edge:
    image: selenium/node-edge:latest
    networks:
      - jenkins-selenium
    container_name: edge
    shm_size: 1gb
    depends_on:
      - selenium-hub
    platform: linux/amd64
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4